/**
 * `@hearth/templates` — genre starter templates.
 *
 * Each template is a small, playable Hearth project (checked in under
 * `templates/<name>`, generated by `generate.mjs`) that teaches one genre's
 * core pattern: a scene, a camera, a player with a comment-annotated Lua
 * movement script, a few obstacles, and a `smoke` playtest. `hearth init`
 * and the editor consume `listTemplates`/`getTemplatePath`/`applyTemplate`
 * to scaffold a new project from one.
 */
import { accessSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export type TemplateName = 'platformer' | 'topdown' | 'arcade';

export interface TemplateInfo {
  name: TemplateName;
  description: string;
}

/**
 * The available templates, in menu order. Descriptions here are the same
 * strings the generator writes into each project's `hearth.json`, so the
 * picker and the scaffolded project always agree.
 */
const TEMPLATES: readonly TemplateInfo[] = [
  {
    name: 'platformer',
    description: 'A side-scrolling platformer skeleton: gravity, jump, and an autotiled ground strip.',
  },
  {
    name: 'topdown',
    description: 'A top-down movement skeleton: four-direction walking, camera follow, and an autotiled room.',
  },
  {
    name: 'arcade',
    description: 'A fixed-camera arcade skeleton: a ship, shoot-on-key bullets, and a spawned target prefab.',
  },
];

/** List the genre starter templates (fresh copies; safe to mutate). */
export function listTemplates(): TemplateInfo[] {
  return TEMPLATES.map((t) => ({ ...t }));
}

/**
 * Candidate on-disk locations for a template, in resolution order — mirrors
 * the web-player bundle resolution in `@hearth/core/node`:
 *   1. `$HEARTH_TOOLS_DIR/templates/<name>` (packaged desktop app / downloads)
 *   2. package-relative `templates/<name>` (repo checkout / installed package;
 *      `import.meta.url` is `dist/index.js` in a build, `src/index.ts` under
 *      vitest — the `templates` dir is a sibling of both).
 */
export function templatePathCandidates(name: string): string[] {
  const candidates: string[] = [];
  const toolsDir = process.env.HEARTH_TOOLS_DIR;
  if (toolsDir) candidates.push(path.join(toolsDir, 'templates', name));
  const here = path.dirname(fileURLToPath(import.meta.url));
  candidates.push(path.resolve(here, '..', 'templates', name));
  return candidates;
}

/**
 * Resolve the directory of a named template. Returns the first candidate that
 * exists on disk. Throws with the checked locations when none is found (same
 * shape as `loadPlayerBundle`).
 */
export function getTemplatePath(name: string): string {
  const candidates = templatePathCandidates(name);
  for (const candidate of candidates) {
    try {
      accessSync(candidate);
      return candidate;
    } catch {
      /* try the next location */
    }
  }
  throw new Error(
    `Hearth template "${name}" not found. Looked in: ${candidates.join(', ') || '(no known locations)'}. ` +
      'Set HEARTH_TOOLS_DIR to a directory containing templates/<name>, or install @hearth/templates.',
  );
}

export { applyTemplate, type ApplyTemplateOptions, type ApplyTemplateResult } from './apply.js';
