import { describe, it, expect } from 'vitest';
import {
  N,
  NE,
  E,
  SE,
  S,
  SW,
  W,
  NW,
  computeMask,
  canonicalMask,
  maskToShape,
  resolveTileFrame,
  resolvedMapping,
  AUTOTILE_SHAPES,
  BLOB47_TEMPLATE,
} from './autotile.js';

/**
 * Independent golden reference for the 47 canonical blob masks (ascending).
 * Regenerated by hand from the bit order N=1,NE=2,E=4,SE=8,S=16,SW=32,W=64,
 * NW=128 with each corner bit dropped unless both its edges are set. If the
 * bit numbering or corner rule ever changes, this list must change with it —
 * that is the point of pinning it here rather than recomputing it.
 */
const GOLDEN_47 = [
  0, 1, 4, 5, 7, 16, 17, 20, 21, 23, 28, 29, 31, 64, 65, 68, 69, 71, 80, 81, 84, 85, 87, 92, 93, 95,
  112, 113, 116, 117, 119, 124, 125, 127, 193, 197, 199, 209, 213, 215, 221, 223, 241, 245, 247,
  253, 255,
];

describe('autotile bit order', () => {
  it('uses the canonical bit values', () => {
    expect([N, NE, E, SE, S, SW, W, NW]).toEqual([1, 2, 4, 8, 16, 32, 64, 128]);
  });
});

describe('canonicalMask corner reduction (256 -> 47)', () => {
  it('collapses all 256 raw masks onto exactly the 47 golden shapes', () => {
    const set = new Set<number>();
    for (let m = 0; m < 256; m++) set.add(canonicalMask(m));
    const got = [...set].sort((a, b) => a - b);
    expect(got).toEqual(GOLDEN_47);
    expect(got).toHaveLength(47);
  });

  it('is idempotent — every canonical mask reduces to itself', () => {
    for (const m of GOLDEN_47) expect(canonicalMask(m)).toBe(m);
  });

  it('never leaves a corner bit set unless both its edge neighbours are set', () => {
    const corners: Array<[number, number]> = [
      [NE, N | E],
      [SE, S | E],
      [SW, S | W],
      [NW, N | W],
    ];
    for (let m = 0; m < 256; m++) {
      const c = canonicalMask(m);
      for (const [corner, edges] of corners) {
        if (c & corner) expect(c & edges).toBe(edges);
      }
    }
  });

  it('drops a lone corner with neither edge (NE alone -> 0)', () => {
    expect(canonicalMask(NE)).toBe(0);
  });

  it('drops a corner with only one adjacent edge (N|NE -> N)', () => {
    expect(canonicalMask(N | NE)).toBe(N);
    expect(canonicalMask(E | NE)).toBe(E);
  });

  it('keeps a corner when both adjacent edges are set (N|E|NE stays)', () => {
    expect(canonicalMask(N | E | NE)).toBe(N | E | NE);
  });

  it('leaves an edge-only mask (N|E, corner absent) untouched', () => {
    expect(canonicalMask(N | E)).toBe(N | E);
  });
});

describe('AUTOTILE_SHAPES / BLOB47_TEMPLATE', () => {
  it('lists the 47 shape keys ascending, unique, matching the golden set', () => {
    expect(AUTOTILE_SHAPES).toEqual(GOLDEN_47.map(String));
    expect(new Set(AUTOTILE_SHAPES).size).toBe(47);
  });

  it('provides a template frame name for every shape and nothing else', () => {
    expect(Object.keys(BLOB47_TEMPLATE).sort()).toEqual([...AUTOTILE_SHAPES].sort());
    expect(BLOB47_TEMPLATE['0']).toBe('blob_0');
    expect(BLOB47_TEMPLATE['255']).toBe('blob_255');
  });
});

describe('computeMask', () => {
  it('treats every off-grid neighbour as SAME (1x1 grid -> fully surrounded)', () => {
    expect(computeMask(['G'], 0, 0, 'G')).toBe(255);
  });

  it('out-of-bounds counts as same at the TOP edge', () => {
    // Middle of top row: N, NE, NW are off-grid (same); E/S/W and their
    // in-grid diagonals are all 'G' too -> fully surrounded.
    const grid = ['GGG', 'GGG'];
    expect(computeMask(grid, 0, 1, 'G')).toBe(255);
  });

  it('out-of-bounds counts as same at the BOTTOM edge', () => {
    const grid = ['GGG', 'GGG'];
    expect(computeMask(grid, 1, 1, 'G')).toBe(255);
  });

  it('out-of-bounds counts as same at the LEFT edge', () => {
    const grid = ['GG', 'GG', 'GG'];
    expect(computeMask(grid, 1, 0, 'G')).toBe(255);
  });

  it('out-of-bounds counts as same at the RIGHT edge', () => {
    const grid = ['GG', 'GG', 'GG'];
    expect(computeMask(grid, 1, 1, 'G')).toBe(255);
  });

  it('a lone tile among empties has mask 0', () => {
    const grid = ['...', '.G.', '...'];
    expect(computeMask(grid, 1, 1, 'G')).toBe(0);
  });

  it('sets exactly the neighbour bits that match the char (interior)', () => {
    // Center 'G' with only its N and E neighbours also 'G'. NE is empty, so
    // the raw mask carries N|E only (the corner never gets set here).
    const grid = ['.G.', '.GG', '...'];
    expect(computeMask(grid, 1, 1, 'G')).toBe(N | E);
  });

  it('sets the NE corner bit when the diagonal matches', () => {
    const grid = ['.GG', '.GG', '...'];
    // N, NE, E all 'G'.
    expect(computeMask(grid, 1, 1, 'G')).toBe(N | NE | E);
  });

  it('only counts the queried char, not other non-empty tiles', () => {
    const grid = ['WWW', 'WGW', 'WWW'];
    expect(computeMask(grid, 1, 1, 'G')).toBe(0);
  });

  it('is pure — does not mutate the grid', () => {
    const grid = ['...', '.G.', '...'];
    const snapshot = JSON.parse(JSON.stringify(grid));
    computeMask(grid, 1, 1, 'G');
    expect(grid).toEqual(snapshot);
  });
});

describe('resolveTileFrame', () => {
  const rule = { sheet: 'ast_ground', template: 'blob47' as const };

  it('resolves a fully-surrounded tile (mask 255) to the template frame', () => {
    expect(resolveTileFrame(rule, 255)).toEqual({ sheet: 'ast_ground', frame: 'blob_255' });
  });

  it('resolves a lone tile (mask 0) to blob_0', () => {
    expect(resolveTileFrame(rule, 0)).toEqual({ sheet: 'ast_ground', frame: 'blob_0' });
  });

  it('reduces the raw mask before lookup (lone corner ignored)', () => {
    // NE alone reduces to shape 0.
    expect(resolveTileFrame(rule, NE).frame).toBe('blob_0');
  });

  it('applies a mapping override for a specific shape, template for the rest', () => {
    const custom = { sheet: 'ast_ground', template: 'blob47' as const, mapping: { '255': 'center' } };
    expect(resolveTileFrame(custom, 255).frame).toBe('center');
    expect(resolveTileFrame(custom, 0).frame).toBe('blob_0');
  });
});

describe('resolvedMapping', () => {
  it('returns the template merged with overrides (47 entries)', () => {
    const merged = resolvedMapping({ sheet: 'x', template: 'blob47', mapping: { '0': 'lonely' } });
    expect(Object.keys(merged)).toHaveLength(47);
    expect(merged['0']).toBe('lonely');
    expect(merged['255']).toBe('blob_255');
  });
});

describe('maskToShape', () => {
  it('returns the canonical mask as a decimal string', () => {
    expect(maskToShape(255)).toBe('255');
    expect(maskToShape(NE)).toBe('0');
    expect(maskToShape(N | NE)).toBe('1');
  });
});
