/**
 * Agent integration files generated into every new Hearth project.
 * These teach coding agents (Claude Code, Codex, any MCP client) how to work
 * on the project safely through structured engine operations.
 */
import { HEARTH_VERSION } from './schema/project.js';

export function generateAgentsMd(projectName: string): string {
  return `# Working on "${projectName}" (a Hearth project)

This directory is a **Hearth** game project. Hearth is an open-source,
agent-native 2D game engine: the entire editor/runtime is exposed through a
structured CLI (\`hearth\`) and an MCP server (\`hearth-mcp\`) so coding agents
can inspect, modify, test, and build this game through safe engine
operations instead of hand-editing JSON.

## Golden rules

1. **Do not guess the project structure.** Inspect first:
   - \`hearth inspect project --json\`
   - \`hearth inspect scenes --json\`
   - \`hearth inspect scene <scene> --json\`
   - \`hearth inspect entity <scene> <entity> --json\`
   - \`hearth inspect components --json\` (all component types + default values)
2. **Prefer structured commands over editing project JSON by hand.**
   The CLI validates every change against schemas. Direct edits to
   \`hearth.json\`, \`scenes/*.scene.json\`, or \`assets.json\` can corrupt the
   project. Scripts in \`scripts/*.js\` are normal code — edit those freely
   (or via \`hearth create script\` / \`hearth edit-script\`).
3. **Snapshot before you change anything:** \`hearth snapshot\`.
   Then the human can review your work with \`hearth diff\` (or the editor's
   Diff panel), and \`hearth revert --confirm\` can undo it.
4. **Validate after changes:** \`hearth validate --json\`. Fix errors you introduced.
5. **Playtest your work:** \`hearth playtest <name>\` runs headless scripted
   tests; \`hearth run <scene> --frames 120\` smoke-runs a scene and reports
   script errors.
6. **Do not delete assets or scenes unless explicitly asked.**
7. **Summarize your changes** when done: which scenes, entities, components,
   scripts, and assets you touched (\`hearth diff --json\` gives you the list).

## Typical workflow

\`\`\`bash
hearth snapshot                        # checkpoint for diff/review
hearth inspect project --json          # learn the project
hearth inspect scene level_1 --json    # learn the scene
hearth create entity level_1 Coin --components '{"SpriteRenderer":{"shape":"circle","color":"#f1c40f"}}'
hearth set level_1 Coin Transform.position.x 200
hearth create script coin-spin
hearth attach script level_1 Coin scripts/coin-spin.js
hearth validate --json                 # must pass
hearth run level_1 --frames 120 --json # no script errors
hearth diff                            # review what changed
\`\`\`

## Project layout (do not restructure)

- \`hearth.json\` — project manifest (scenes list, input mappings, build settings)
- \`scenes/*.scene.json\` — scene files (entities + components)
- \`assets.json\` — asset index; \`assets/\` — asset files
- \`scripts/*.js\` — behavior scripts (see script template docs: \`hearth inspect components\`)
- \`playtests/*.playtest.json\` — headless playtest definitions
- \`.hearth/\` — engine state (baseline snapshots, agent config); don't edit manually

## Scripting quick reference

Scripts export default an object with \`onStart(ctx)\`, \`onUpdate(ctx, dt)\`,
\`onCollision(ctx, other)\`. \`ctx\` gives you: \`entity\`, \`transform\`,
\`getComponent(type)\`, \`params\`, \`input.isDown/justPressed(action)\`,
\`scene.find(name)/findByTag(tag)/spawn(def)/destroy(ref)\`, \`vars\`
(persistent per-entity state), \`time\`, \`log(...)\`.

Input actions are defined in \`hearth.json\` under \`inputMappings.actions\`
(\`hearth inspect project --json\` shows them; \`hearth set-input <action> <keys...>\` changes them).

## MCP

If you are connected via MCP instead of the CLI, the same operations are
exposed as tools (\`get_project_info\`, \`inspect_scene\`, \`create_entity\`,
\`set_component_property\`, \`run_playtest\`, \`get_diff\`, ...). Call
\`get_agent_instructions\` for this document.

Generated by Hearth ${HEARTH_VERSION}.
`;
}

export function generateClaudeMd(projectName: string): string {
  return `# CLAUDE.md — ${projectName}

This is a Hearth game project. **Read AGENTS.md for the full agent guide.**

Quick facts:
- Use the \`hearth\` CLI (with \`--json\`) for all project operations; do not hand-edit
  \`hearth.json\`, \`scenes/*.scene.json\`, or \`assets.json\`.
- \`hearth snapshot\` before changes; \`hearth validate --json\` and \`hearth diff\` after.
- Behavior code lives in \`scripts/*.js\` — normal JavaScript, edit freely.
- Test with \`hearth playtest <name>\` and \`hearth run <scene> --frames 120 --json\`.
- Never delete assets/scenes without being asked.
`;
}

export function generateAgentConfig(projectName: string, projectId: string) {
  return {
    hearthVersion: HEARTH_VERSION,
    project: projectName,
    projectId,
    instructions: 'AGENTS.md',
    cli: {
      binary: 'hearth',
      jsonFlag: '--json',
      recommendedFirstCommands: [
        'hearth inspect project --json',
        'hearth inspect scenes --json',
        'hearth validate --json',
      ],
    },
    mcp: {
      server: 'hearth-mcp',
      transport: 'stdio',
      note: 'Start with: hearth-mcp --project <this directory> [--mode read-only|safe-edit|code-edit|asset-edit|build|all]',
    },
    permissions: {
      defaultModes: ['read-only', 'safe-edit', 'code-edit', 'asset-edit'],
      buildRequiresOptIn: true,
    },
  };
}
