/**
 * The project digest: a compact, always-current markdown snapshot of project
 * state, generated by the engine after every mutating command (see the hook in
 * `../session.ts`). The agent reads `.hearth/digest.md` at the start of a turn
 * instead of re-running `inspect` on everything — so it never re-derives what it
 * already had, which is the single biggest source of token burn in a long
 * session. It is rendered synchronously from the in-memory `ProjectStore`, so it
 * is exactly as accurate as an inspect; when the agent needs *full* component
 * data for one entity it still inspects that entity.
 *
 * Kept deliberately terse: one line per entity (name + component types + tags +
 * script), grouped by scene. It replaces re-inspection, so smaller is better.
 */
import type { FsLike } from '../fs.js';
import { joinPath } from '../fs.js';
import type { ProjectStore } from './store.js';
import type { Scene, Entity } from '../schema/scene.js';
import { HEARTH_VERSION, DIGEST_FILE } from '../schema/project.js';

/** Component type names present on an entity, with the script path inlined for a Script. */
function componentSummary(entity: Entity): string {
  const types = Object.keys(entity.components ?? {});
  return types
    .map((t) => {
      if (t === 'Script') {
        const path = (entity.components as Record<string, { scriptPath?: string }>).Script?.scriptPath;
        return path ? `Script→${path}` : 'Script';
      }
      return t;
    })
    .join(', ');
}

/** One compact line for an entity, indented by its depth in the hierarchy. */
function entityLine(entity: Entity, depth: number): string {
  const indent = '  '.repeat(depth);
  const comps = componentSummary(entity);
  const tags = (entity.tags ?? []).map((t) => `#${t}`).join(' ');
  const disabled = entity.enabled === false ? ' (disabled)' : '';
  const parts = [`${indent}- **${entity.name}**`];
  if (comps) parts.push(`[${comps}]`);
  if (tags) parts.push(tags);
  return parts.join(' ') + disabled;
}

/** Render a scene's entities as a parent→child tree (roots first, children indented). */
function renderScene(scene: Scene): string {
  const lines: string[] = [];
  const childrenByParent = new Map<string | null, Entity[]>();
  for (const e of scene.entities) {
    const key = e.parentId ?? null;
    const list = childrenByParent.get(key) ?? [];
    list.push(e);
    childrenByParent.set(key, list);
  }
  const walk = (parentId: string | null, depth: number) => {
    for (const e of childrenByParent.get(parentId) ?? []) {
      lines.push(entityLine(e, depth));
      walk(e.id, depth + 1);
    }
  };
  walk(null, 0);
  return lines.join('\n');
}

/**
 * Render the full digest markdown for a project. Pure and synchronous over the
 * in-memory store — no filesystem, no validation, no rendering.
 */
export function generateDigest(store: ProjectStore): string {
  const p = store.project;
  const initial = p.initialScene ? store.scenes.get(p.initialScene)?.name ?? p.initialScene : '(none)';
  const bs = p.buildSettings;
  const actions = Object.entries(p.inputMappings?.actions ?? {});

  const out: string[] = [];
  out.push(`# Project digest — ${p.name}`);
  out.push('');
  out.push(
    '_Engine-generated snapshot of the current project state, refreshed after every change. ' +
      'Read this instead of re-running `inspect` — it is always current. For the full component ' +
      'data of one entity, `inspect entity`. Do not edit this file; it is overwritten._',
  );
  out.push('');
  out.push(`- **Engine:** Hearth ${HEARTH_VERSION}`);
  out.push(`- **Initial scene:** ${initial}`);
  out.push(`- **Resolution:** ${bs.width}×${bs.height} · pixelPerfect ${bs.pixelPerfect ? 'on' : 'off'}`);
  if (actions.length) {
    out.push(`- **Input actions:** ${actions.map(([name, keys]) => `${name} (${keys.join(', ')})`).join(' · ')}`);
  }

  // Scenes with their entity trees.
  out.push('');
  out.push(`## Scenes (${p.scenes.length})`);
  for (const ref of p.scenes) {
    const scene = store.scenes.get(ref.id);
    if (!scene) continue;
    out.push('');
    out.push(`### ${scene.name} — ${scene.entities.length} entities`);
    const body = renderScene(scene);
    if (body) out.push(body);
  }

  // Assets grouped by type.
  const byType = new Map<string, string[]>();
  for (const a of store.assets.assets) {
    const list = byType.get(a.type) ?? [];
    list.push(a.name);
    byType.set(a.type, list);
  }
  out.push('');
  out.push(`## Assets (${store.assets.assets.length})`);
  if (byType.size === 0) {
    out.push('_None yet._');
  } else {
    for (const [type, names] of [...byType].sort()) {
      out.push(`- **${type}** (${names.length}): ${names.join(', ')}`);
    }
  }

  // Playtests.
  out.push('');
  out.push(`## Playtests (${store.playtests.size})`);
  if (store.playtests.size === 0) {
    out.push('_None yet — add one to prove behavior headlessly._');
  } else {
    for (const pt of store.playtests.values()) {
      out.push(`- ${pt.name}`);
    }
  }

  return out.join('\n') + '\n';
}

/**
 * Write the digest to `.hearth/digest.md`. Best-effort: a failure here must
 * never turn a successful command into a failed one, so it swallows errors (the
 * caller in `session.execute` treats this as a fire-and-forget side effect, the
 * same way it isolates history and journal writes).
 */
export async function writeDigest(fs: FsLike, root: string, store: ProjectStore): Promise<void> {
  try {
    const md = generateDigest(store);
    await fs.mkdir(joinPath(root, '.hearth'));
    await fs.writeFile(joinPath(root, DIGEST_FILE), md);
  } catch {
    // Intentionally ignored — the digest is a convenience cache, not project data.
  }
}
